dna = 'TCAATGCATGCGGGTCTATATGCAT'
dna = 'ATATAAATTCCCGGATTGGAGCCCAGGGACGGTGTTGTCTTGGTTTAAATAGATAATGCTTGTTTTAGGCTTTGCTACAGGGATTAGCAACATTTCTGCCGGCTCTCAATCGTAAGGTTATGAGTGGTATGCGAGCGGATTGAAAAAGGGCTAAATATTTTCATCCAAGGACACACTACGACTTGGATGTTTGCTGGCCCGTCCAAATTGAAGCCGGAAATACCCTATTGGAGGATATGGGAATGCGCAGTACGTCCGTAAATTAAAGATTCTTTCTTTTTTTTGCACTAGCCCTAGACGGCCAAATAAAACAAGAGGACTTGGCAATCATGAAGTCAACAGAAGAACTGTCTATAAGGCCCTATGAACTCAGTTTGCGTCTACCAGTATGTACCACTGTTCTAATTTTCTCATGGACATGCTTGAGAGAAGAGGTTTTATGCGTCGGTAGAGTGGATAATGAGGGTTTCTCGTATCGCGCGATATCGTAAGGATCTGTTTATGACCGGATCCTCCACATGAACAGATTATATTCCACGATGTTTCATGTGGTTTAGCGATTAGCTAAAGTGACAGCCACCCCACCCTCTCTGGTTCCCCCGCCGCCACGCGAAGCCCGCTTTTGTCACGCCGCATCACGAATCTTGGAGCGGACGCTTCGGGTTGACAGGTATGTGCGATGTGACGGCCTTACAGACGCGGGGGATCGTGGGCCGCGCGCTCCCTTCGTTCACTTTTAGTTCGGGTCCTTCCATTGGGCAACCATTCTTGCGAATGTATTGATCAAACGTGATACCGCGAACAGTGCCGTTACCACTACTCATGGACGCGAGGCACAGCCACACCGACTCTATGCAAATTACTAGGGAGCGAACAAAATGCGGATCGAGGCGATACTTAGCGATCCTACTGTTGATGGCCAGCTCGGACACAGAATTCTAGACCCGTGCGGTTCGCG'
def reverse( str ):
    res = ''
    for i in str:
        res = i + res
    return res

def compliment( str ):
    res = ''
    dict = {'A':'T', 'T':'A', 'G':'C', 'C':'G'}
    for i in str:
        res += dict[i]
    return res


for i in range(4,13):
    j = 0
    #print "out: ", i
    while j+i <= len(dna):
        seg = dna[j:j+i]
        #print "in: ", i, j, i+j, seg, reverse(seg), compliment( seg )
        if compliment(seg) == reverse(seg):
            print j+1, i
        j += 1
